main/urls.py
from django.urls import path
from .views import *

app_name="main"

urlpatterns = [
    path('',mainpage,name="mainpage"),
    path('second',secondpage,name="secondpage"),
    path('new-post',new_post,name="new-post"),
    path('create',create,name="create"),
    path('<int:id>',detail,name="detail"),
    path('edit/<int:id>',edit,name="edit"),
    path('update/<int:id>',update,name="update"),
    path('delete/<int:id>',delete,name="delete"),
    path('delete/comment/<int:id>',delete_comment,name="delete_comment"),
    path('tag-list', tag_list,name="tag-list"),
    path('tag-post/<int:tag_id>',tag_posts,name="tag-posts"),
    path('likes/<int:post_id>',likes,name="likes"),
    ]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from main import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('accounts/',include('accounts.urls')),
    path('users/',include('users.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *

app_name="users"
urlpatterns=[
    path('mypage/<int:id>',mypage,name="mypage"),
    path('follow/<int:id>',follow,name="follow"),
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib import auth
from django.contrib.auth.models import User
from main.models import Post


# Create your views here.
def mypage(request,id):
    user=get_object_or_404(User,pk=id)
    posts=Post.objects.filter(writer=user)
    context={
        'user':user,
        'posts' :posts,
    }
    return render(request,'users/mypage.html',context)

def follow(request,id):
    user=request.user
    followed_user=get_object_or_404(User,pk=id)
    is_follower=user.profile in followed_user.profile.followers.all()
    if is_follower:
        user.profile.followings.remove(followed_user.profile)
    else:
        user.profile.followings.add(followed_user.profile)
    return redirect('users:mypage',followed_user.id)

users/templates/users/mypage.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>{{user.username}}님의 마이페이지</h1>

<h3>{{user.username}}님 안녕하세요</h3>
<h3>당신의 이메일은 {{user.profile.email_address}}입니다.</h3>
User : {{user}} <br>
UserProfile : {{user.profile}} <br>
<p>팔로워<br>{{ user.profile.followers.count}}명</p>
<p>팔로잉<br>{{ user.profile.followings.count}}명</p>
{% if request.user != user %}
{% if request.user.profile in user.profile.followers.all %}
<a href="{% url 'users:follow' user.id %}">
    <button type="button" class="btn btn-outline-info">언팔로우</button>
</a>
{% else %}
<a href="{% url 'users:follow' user.id %}">
    <button type="button" class="btn btn-info">팔로우</button>
</a>
{% endif %}
{% endif %}
<h3>당신이 작성한 블로그 목록</h3>
<ul>
    {% for post in posts %}
    <li>
        <a href="{% url 'main:detail' post.id %}">{{ post.title }}</a>
        <p>{{ post.writer }}</p>
    </li>
    {% endfor %}
</ul>



{% endblock %}