main/urls.py
from django.urls import path
from .views import *

app_name="main"

urlpatterns = [
    path('',mainpage,name="mainpage"),
    path('second',secondpage,name="secondpage"),
    path('new-post',new_post,name="new-post"),
    path('create',create,name="create"),
    path('<int:id>',detail,name="detail"),
    path('edit/<int:id>',edit,name="edit"),
    path('update/<int:id>',update,name="update"),
    path('delete/<int:id>',delete,name="delete"),
    path('delete/comment/<int:id>',delete_comment,name="delete_comment"),
    path('tag-list', tag_list,name="tag-list"),
    path('tag-post/<int:tag_id>',tag_posts,name="tag-posts"),
    path('likes/<int:post_id>',likes,name="likes"),
    ]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from main import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('accounts/',include('accounts.urls')),
    path('users/',include('users.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *

app_name="users"
urlpatterns=[
    path('mypage/<int:id>',mypage,name="mypage"),
    path('follow/<int:id>',follow,name="follow"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Tag(models.Model):
    name=models.CharField(max_length=30,null=False,blank=False)

    def __str__(self):
        return self.name

class Post(models.Model):
    title=models.CharField(max_length=30)
    writer=models.ForeignKey(User,null=False,blank=False,on_delete=models.CASCADE)
    content=models.TextField()
    created_time=models.DateTimeField()
    updated_time=models.DateTimeField()
    feeling=models.CharField(max_length=10)
    image = models.ImageField(upload_to="post/",blank=True,null=True)
    tags=models.ManyToManyField(Tag,related_name='posts',blank=True)
    like=models.ManyToManyField(User,related_name='likes',blank=True)
    like_count=models.PositiveIntegerField(default=0)


    def __str__(self):
        return self.title

    def summary(self):
        return self.content[:3]

class Comment(models.Model):
    content=models.TextField()
    pub_date=models.DateTimeField()
    writer=models.ForeignKey(User,null=False,blank=False,on_delete=models.CASCADE)
    post=models.ForeignKey(Post,null=False,blank=False,on_delete=models.CASCADE)

    def __str__(self):
        return self.blog.title+":"+self.content[:20]+"by"+self.writer.profile.nickname

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from .models import *

# Create your views here.


def mainpage(request):
    context = {
        "generation": 13,
        "info": {"weather": "좋음", "feeling": "배고픔(?)", "note": "아기사자 화이팅!"},
        "shortKeys": [
            "들여쓰기: Tab",
            "내어쓰기: Shift + Tab",
            "주석처리: 윈도우-Ctrl + /, 맥-command + /",
            "자동정렬: Shift + Alt + F or Ctrl + K + F",
            "한줄이동: Alt + 방향키(위/아래)",
            "한줄삭제: Ctrl + Shift + k or Ctrl + x",
            "같은단어전체선택: Ctrl + Shift + L",
        ]
    }
    return render(request, "main/mainpage.html", context)


def secondpage(request):
    posts=Post.objects.all()
    return render(request, "main/secondpage.html",{'posts':posts})

def new_post(request):
    return render(request,'main/hdpost.html')

def detail(request,id):
    post = get_object_or_404(Post, pk=id)
    if request.method=='GET':
        comments=Comment.objects.filter(post=post)
        return render(request,'main/detail.html',{'post':post,'comments':comments})

    elif request.method=='POST':
        new_comment=Comment()
        new_comment.post=post
        new_comment.writer=request.user
        new_comment.content=request.POST['content']
        new_comment.pub_date=timezone.now()
        new_comment.save()
        return redirect('main:detail',id)

def create(request):
    if request.user.is_authenticated:
        new_post = Post()

        new_post.title = request.POST['title']
        new_post.writer = request.user
        new_post.content = request.POST['content']
        new_post.feeling = request.POST['feeling']
        new_post.created_time = timezone.now()
        new_post.updated_time = timezone.now()
        new_post.image=request.FILES.get('image')

        new_post.save()

        words=new_post.content.split()
        tag_list=[]

        for w in words:
            if len(w)>0:
                if w[0]=='#':
                    tag_list.append(w[1:])  
        for t in tag_list:
            tag,boolean=Tag.objects.get_or_create(name=t)
            new_post.tags.add(tag.id)

        return redirect('main:detail',new_post.id)
    else:
        return redirect('accounts:login')

def edit(request,id):
    edit_post=Post.objects.get(pk=id)
    return render(request,'main/edit.html',{"post":edit_post})

def update(request,id):
    update_post=Post.objects.get(pk=id)
    if request.user.is_authenticated and request.user==update_post.writer:
        update_post.title=request.POST['title']
        update_post.content=request.POST['content']
        update_post.feeling=request.POST['feeling']
        update_post.updated_time=timezone.now()
        
        words=update_post.content.split()
        tag_list=[]

        for w in words:
            if len(w)>0:
                if w[0]=='#':
                    tag_list.append(w[1:])
        for t in tag_list:
            tag,boolean=Tag.objects.get_or_create(name=t)
            update_post.tags.add(tag.id)

        if request.FILES.get('image'):
            update_post.image=request.FILES.get('image')
        update_post.save()
        return redirect('main:detail',update_post.id)
    return redirect('accounts:login',update_post.id)

def delete(request,id):
    delete_post=Post.objects.get(pk=id)
    delete_post.delete()
    return redirect('main:secondpage')

def delete_comment(request,id):
    comments = get_object_or_404(Comment,pk=id)
    post_id=comments.post.id
    comments.delete()
    return redirect('main:detail',post_id)

def tag_list(request): #모든 태그 목록을 볼 수 있는 페이지
    tags=Tag.objects.all()
    return render(request,'main/tag-list.html',{'tags':tags})

def tag_posts(request,tag_id): #특정 태그를 가진 게시글의 목록을 볼 수 있는 페이지
    tag=get_object_or_404(Tag,id=tag_id)
    posts=tag.posts.all()
    return render(request,'main/tag-post.html',{'tag':tag,'posts':posts})

def likes(request,post_id):
    post = get_object_or_404(Post,id=post_id)

    if request.user in post.like.all():
        post.like.remove(request.user)
        post.like_count -=1
        post.save()
    else:
        post.like.add(request.user)
        post.like_count+=1
        post.save()
    return redirect('main:detail',post.id)

main/templates/main/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3>{{post.title}}</h3>
<a href="{% url 'users:mypage' post.writer.id %}">작성자:{{post.writer.id}}</a>
작성자 : {{post.writer}}
<a href="{% url 'main:likes' post.id %}">
    {% if user in post.like.all %} 취소 {% else %} 좋아요 {% endif %}
</a>{{post.like_count}}개
<br>
작성 시각 : {{post.created_time}}<br>
수정 시각 : {{post.updated_time}}
<p>
    {% for tag in post.tags.all %}
    <a href="{% url 'main:tag-posts' tag.id %}">#{{tag.name}}</a>
    {% endfor %}
</p>
<hr />
{% if post.image %}
<p><img src="{{post.image.url}}" alt="사진" width="200px" </p>
    {% endif %}
<p>{{post.content|linebreaksbr}}</p>
<p>오늘의 기분: {{post.feeling}}</p>
{% if post.writer == user %}
<a href="{% url 'main:edit' post.id %}">글 수정</a>
<a href="{% url 'main:delete' post.id %}">글 삭제</a>
{% endif %}
<br>
<div class="comment_container">
    <div class="comment_form">
        <h2></h2>
        <form action="{% url 'main:detail' post.id %}" method="POST">
            {% csrf_token %}
            댓글 쓰기:<input type="text" name="content">
            <input type="submit" name="submit">
        </form>
    </div>
    <div class="comment_list">
        {% for comment in comments %}
        <hr>
        <h4>작성자: {{comment.writer}}</h4>
        <p>내용: {{comment.content}}</p>
        <p>{{comment.pub_date}}</p>
        {% if comment.writer == user %}
        <a href="{% url 'main:delete_comment' comment.id %}">댓글 삭제</a>
        {% endif %}
        {% endfor %}
    </div>
</div>

{% endblock %}

main/templates/main/edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>수정중!</h2>
<form action="{% url 'main:update' post.id %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p>제목: <input type="text" name="title" value="{{post.title}}"></p>
    <p>작성자: <input type="text" name="writer" value="{{post.writer}}"></p>
    {% if post.image %}
    <p><img src="{{post.image.url}}" alt="사진" width="200px"></p>
    {% endif %}
    <p>사진: <input type="file" name="image"></p>
    <p>글내용: <textarea type="text" name="content" id="" cols="50" rows="10">{{post.content}}</textarea></p>
    <p>기분이 바뀌셨나요? <input type="text" name="feeling" value="{{post.feeling}}"></p>
    <button type="submit">제출</button>
</form>
{% endblock %}

main/templates/main/hdpost.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<form action="{% url 'main:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p>제목: <input type="text" name="title"></p>
    <!-- <p>작성자: <input type="text" name="writer"></p>-->
    <p>사진: <input type="file" name="image"></p>
    <p>글내용: <textarea type="text" name="content" id="" cols="50" rows="10"></textarea></p>
    <p>오늘의 기분: <input type="text" name="feeling"></p>
    <button type="submit">조효동 파이팅!</button>
</form>

{% endblock %}

main/templates/main/mainpage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<img src="{% static 'images/logo.png' %}" alt="logo" width="100px">
{% if request.user.profile.profile_image %}
<p><img src="{{ request.user.profile.profile_image.url}}" alt="프로필 사진" width="100px"></p>
<p><strong>프로필 사진</strong></p>
{% endif %}
<h1 class="contents">2025 멋쟁이사자처럼 {{ generation }}기</h1>
<div class="contents">Welcome Django!</div>
<div>🦁 머쩅이 사자의 일기짱🦁 </div>
<ul>
    <li>오늘의 날씨 : {{ info.weather }}</li>
    <li>오늘의 기분 : {{ info.feeling }}</li>
    <li>{{ info.note }}</li>
</ul>
<div>🦁 VS Code 단축키🦁 </div>
<ul>
    {% for shortKey in shortKeys %}
    <li>{{ shortKey }}</li>
    {% endfor %}
</ul>

{% endblock %}

main/templates/main/secondpage.html
{% extends 'base.html' %}
{% block content %}

<h1 class="contents">2025 멋쟁이사자처럼 13기</h1>
<div class="contents">This is Second Page</div>
<div>
    <div>
        {% if user.is_authenticated %}
        <a href="{% url 'main:new-post' %}">새 글 작성하기</a>
        {% endif %}
    </div>
    {% for post in posts %}
    <div>
        <hr />
        <h3>{{post.title}}</h3>
        {{post.writer}} | {{post.created_time}}<br>
        {{post.content|linebreaksbr}}<br>
        <br>오늘의 기분: {{post.feeling}}
        <p>포스트 내용 요약: {{post.summary}}</p>
        <a href="{% url 'main:detail' post.id %}">자세히 볼까요?</a>
        <br>
    </div>
    {% endfor %}
</div>

{% endblock %}

main/templates/main/tag-list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <h1>해시태그 목록</h1>
    <hr>
    {% for t in tags %}
    <div>
        <h2><a href="{% url 'main:tag-posts' t.id %}">#{{t.name}}</a></h2>
    </div>
    {% endfor %}
</div>
{% endblock %}

main/templates/main/tag-post.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <h1>#{{tag}}가 달린 게시글</h1>
    <hr>
    <div>
        {% for p in posts %}
        <hr />
        <h3>{{p.title}}</h3>
        {{p.writer}} | 작성 시각: {{p.created_time}} | 수정 시각: {{p.updated_time}}<br>
        {{p.summary}}
        <a href="{% url 'main:detail' p.id %}">자세히 보기</a>
        <br>
        {% endfor %}
    </div>
</div>
{% endblock %}